"""Criação inicial das tabelas

Revision ID: ff38e44389f0
Revises: 
Create Date: 2025-11-01 21:42:31.247201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff38e44389f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('casos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_solicitante', sa.String(length=255), nullable=False),
    sa.Column('ramal', sa.String(length=20), nullable=True),
    sa.Column('secretaria', sa.String(length=255), nullable=True),
    sa.Column('departamento', sa.String(length=255), nullable=True),
    sa.Column('numero_patrimonio', sa.String(length=50), nullable=False),
    sa.Column('problema_descricao', sa.Text(), nullable=True),
    sa.Column('solucao_descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ultima_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('casos')
    op.drop_table('avisos')
    # ### end Alembic commands ###
